services:
  - type: web
    name: sistema-moeda-backend
    env: docker
    plan: free
    rootDir: backend
    autoDeploy: true

    envVars:
      # DATABASE (Neon) -------------------------
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-calm-cake-aeeg1sxq-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner

      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_6PyZC1DsjxEJ

      # EMAIL ------------------------------------
      - key: MAIL_USERNAME
        value: arthurpedrasantana@gmail.com

      - key: MAIL_PASSWORD
        value: vicfvqlcpyzuvtib
